language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env:
  - VAULT_ADDR=http://localhost:8200
before_script:
  - wget https://releases.hashicorp.com/vault/0.4.0/vault_0.4.0_linux_amd64.zip
  - unzip vault_0.4.0_linux_amd64.zip
  - ./vault server -dev
  - ./vault auth-enable userpass
  - ./vault write auth/userpass/users/rickfast password=foo policies=root
script: mvn clean test
