language: java
jdk:
  - oraclejdk8
env:
  - VAULT_ADDR=http://localhost:8200
sudo: required
services:
  - docker
before_script:
  - docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -d -p 127.0.0.1:3306:3306 mysql
  - wget https://releases.hashicorp.com/vault/0.4.0/vault_0.4.0_linux_amd64.zip
  - unzip vault_0.4.0_linux_amd64.zip
  - ./vault server -dev &
  - ./vault auth-enable userpass
  - ./vault write auth/userpass/users/rickfast password=foo policies=root
  - ./vault mount mysql
  - ./vault write mysql/config/connection connection_url="root:root@tcp(127.0.0.1:3306)/"
  - ./vault write mysql/config/lease lease=1h lease_max=24h
  - ./vault write mysql/roles/readonly sql="CREATE USER '{{name}}'@'%' IDENTIFIED BY '{{password}}';GRANT SELECT ON *.* TO '{{name}}'@'%';"
script: mvn clean test
